In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor,plot_tree

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,f1_score,roc_curve,multilabel_confusion_matrix

from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV

In [2]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
df.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# Train test split

In [5]:
x = df.drop(['Id','Species'],axis=1)
y = df['Species']

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,stratify=y,random_state=45)

In [25]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(105, 4)
(105,)
(45, 4)
(45,)


# Logistic Regression

## model training

In [26]:
logistic_model = LogisticRegression()
logistic_model.fit(x_train,y_train)

LogisticRegression()

## Model evaluation

In [27]:
# testing accuracy

y_pred = logistic_model.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print("confusion matrix is :",cnf_matrix)

print()
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_test,y_pred)
print("classification report \n:",clf_report)

confusion matrix is : [[15  0  0]
 [ 0 14  1]
 [ 0  3 12]]

Accuracy : 0.9111111111111111

classification report 
:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.82      0.93      0.87        15
 Iris-virginica       0.92      0.80      0.86        15

       accuracy                           0.91        45
      macro avg       0.92      0.91      0.91        45
   weighted avg       0.92      0.91      0.91        45



In [28]:
# training accuracy

y_pred_train = logistic_model.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print("confusion matrix is :",cnf_matrix)

print()
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_train,y_pred_train)
print("classification report :",clf_report)

confusion matrix is : [[35  0  0]
 [ 0 34  1]
 [ 0  2 33]]

Accuracy : 0.9714285714285714

classification report :                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        35
Iris-versicolor       0.94      0.97      0.96        35
 Iris-virginica       0.97      0.94      0.96        35

       accuracy                           0.97       105
      macro avg       0.97      0.97      0.97       105
   weighted avg       0.97      0.97      0.97       105



# KNN

In [30]:
knn_classifier = KNeighborsClassifier()
knn_classifier.fit(x_train,y_train)

KNeighborsClassifier()

## Model Evaluation

In [31]:
# testing data
y_pred = knn_classifier.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print("confusion matrix is :",cnf_matrix)
print()
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_test,y_pred)
print("classification report \n:",clf_report)

confusion matrix is : [[15  0  0]
 [ 0 15  0]
 [ 0  3 12]]

Accuracy : 0.9333333333333333

classification report 
:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.83      1.00      0.91        15
 Iris-virginica       1.00      0.80      0.89        15

       accuracy                           0.93        45
      macro avg       0.94      0.93      0.93        45
   weighted avg       0.94      0.93      0.93        45



In [32]:
# training accuracy

y_pred_train = knn_classifier.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print("confusion matrix is :",cnf_matrix)

print()
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_train,y_pred_train)
print("classification report :",clf_report)

confusion matrix is : [[35  0  0]
 [ 0 33  2]
 [ 0  0 35]]

Accuracy : 0.9809523809523809

classification report :                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        35
Iris-versicolor       1.00      0.94      0.97        35
 Iris-virginica       0.95      1.00      0.97        35

       accuracy                           0.98       105
      macro avg       0.98      0.98      0.98       105
   weighted avg       0.98      0.98      0.98       105



## Hyperparameter Tuning

In [35]:
knn_classifier = KNeighborsClassifier()
hyperparameter =  {'n_neighbors':np.arange(3,30),'p':[1,2]}

gscv = GridSearchCV(knn_classifier,hyperparameter,cv=5)
gscv.fit(x_train,y_train)
gscv.best_estimator_

KNeighborsClassifier(n_neighbors=10, p=1)

In [36]:
# testing data
knn_classifier = gscv.best_estimator_
y_pred = knn_classifier.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print("confusion matrix is :",cnf_matrix)
print()
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_test,y_pred)
print("classification report \n:",clf_report)

confusion matrix is : [[15  0  0]
 [ 0 15  0]
 [ 0  3 12]]

Accuracy : 0.9333333333333333

classification report 
:                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.83      1.00      0.91        15
 Iris-virginica       1.00      0.80      0.89        15

       accuracy                           0.93        45
      macro avg       0.94      0.93      0.93        45
   weighted avg       0.94      0.93      0.93        45



In [37]:
# training accuracy

y_pred_train = knn_classifier.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print("confusion matrix is :",cnf_matrix)

print()
accuracy = accuracy_score(y_train,y_pred_train)
print("Accuracy :",accuracy)
print()
clf_report = classification_report(y_train,y_pred_train)
print("classification report :",clf_report)

confusion matrix is : [[35  0  0]
 [ 0 34  1]
 [ 0  2 33]]

Accuracy : 0.9714285714285714

classification report :                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        35
Iris-versicolor       0.94      0.97      0.96        35
 Iris-virginica       0.97      0.94      0.96        35

       accuracy                           0.97       105
      macro avg       0.97      0.97      0.97       105
   weighted avg       0.97      0.97      0.97       105



# User input

In [38]:
SepalLengthCm = 5.1
SepalWidthCm = 3.5
PetalLengthCm = 1.4
PetalWidthCm = 0.2

In [39]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0.])

In [40]:
test_array[0] = SepalLengthCm
test_array[1] = SepalWidthCm
test_array[2] = PetalLengthCm
test_array[3] = PetalWidthCm

In [42]:
json_data = {'columns':list(x.columns)}
json_data

{'columns': ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']}

In [43]:
import pickle
import json

In [44]:
with open("Iris Model.pkl",'wb') as f:
    pickle.dump(knn_classifier,f)

In [45]:
with open("Project Data.json",'w') as f:
    json.dump(json_data,f)